ProjectFinal - MVC/Models/Agent.cs
using System.ComponentModel.DataAnnotations;

namespace ProjectFinal___MVC.Models
{
    public class Agent
    {        
        public int? Id { get; set; }

        public string nickname { get; set; }

        public string? Status { get; set; }

        public int x { get; set; } = 0;

        public int y { get; set; } = 0;

        public string photoUrl { get; set; }
    }
}

ProjectFinal - MVC/Models/ErrorViewModel.cs
namespace ProjectFinal___MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjectFinal - MVC/Models/Mission.cs
namespace ProjectFinal___MVC.Models
{
    public class Mission
    {
        public int Id { get; set; }

        public Agent Agent { get; set; }

        public Target Target { get; set; }

        public double? Duration { get; set; }

        public double TimLeft { get; set; }

        public string Status { get; set; }

        public Mission() { }
    }
}

ProjectFinal - MVC/Models/Target.cs
namespace ProjectFinal___MVC.Models
{
    public class Target
    {
        public int Id { get; set; }

        public string name { get; set; }

        public string position { get; set; }

        public int x { get; set; } = new int();

        public int y { get; set; } = new int();

        public string photoUrl { get; set; }

        public string? Status { get; set; }
    }
}

ProjectFinal - MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectFinal___MVC.Models;
using ProjectFinal___MVC.Service;
using System.Diagnostics;

namespace ProjectFinal___MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, HttpClient httpClient)
        {
            _logger = logger;
            _httpClient = httpClient;
        }

        //מעלה דף בית עם סיכום המצב 
        public async Task<IActionResult> Index()
        {
            var agentsSummary = await _httpClient.GetFromJsonAsync<AgentSummery>("http://localhost:5281/agents/summery");//סיכום סוכנים
            var targetsSummary = await _httpClient.GetFromJsonAsync<TargetSummery>("http://localhost:5281/targets/summery");//סיכום מטרות
            var missionsSummary = await _httpClient.GetFromJsonAsync<MissionSummery>("http://localhost:5281/missions/summery");//סיכום משימות

            var Summery = new Summery((agentsSummary.UnderCover+agentsSummary.OnAmission),
                                        targetsSummary.Alive+targetsSummary.Eliminated,
                                        missionsSummary.Actice+missionsSummary.suggestion
                                        +missionsSummary.Complited);

            Summery.GanaralRatio = $"{agentsSummary.OnAmission+agentsSummary.UnderCover}:{targetsSummary.Alive+targetsSummary.Eliminated}";//חישוב של הסוכנים ביחס למטרות
            
            var availableAgents = await _httpClient.GetFromJsonAsync<AvailableAgents>("http://localhost:5281/missions/ratio");//משיכה של מספר סוכנים שניתן לצוותם למשימה

            Summery.ReleventRatio = $"{availableAgents.availableAgents}:{targetsSummary.Alive}";//הגדרה של יוחס סוכנים שאפשר לצוותם ביחס למטרות

            Summery.ActiveAgents = agentsSummary.OnAmission;
            Summery.ActiveTargets = targetsSummary.Eliminated;
            Summery.ActiveMissions = missionsSummary.Actice;


            return View(Summery);
        }

        //מעלה דף עם כל הסוכנים ומשימותיהם
        public async Task<IActionResult> GetAgents()
        {
            var agents = await _httpClient.GetFromJsonAsync<IEnumerable<Agent>>("http://localhost:5281/Agents");
            var missions = await _httpClient.GetFromJsonAsync<IEnumerable<Mission>>("http://localhost:5281/Missions");

            AgentWithMission dicAgents = new AgentWithMission();//מילון שיכיל את הסוכן ואת הריגותיו ומשימתו הפעילה אם יש
            

            foreach (Agent agent in agents)
            {
                MissionSumKills missionSumKills = new MissionSumKills();//מבנה נתונים המכיל משימה פעילה אם יש, וסכום ההריגות
                var missionsByAgentId = missions.Where(miss => miss.Agent.Id == agent.Id);//משיכה של כל המשימות של הסוכן
                if (missionsByAgentId != null)
                {
                    missionSumKills.sumKills = missionsByAgentId.Count(mis => mis.Status == "Comlpeted");
                    foreach (var mission in missionsByAgentId)
                    {                        
                        //מצרף למילון את המשימה הפעילה אם קיימת
                        if (mission.Status == "Actice")
                        {
                            missionSumKills.mission = mission;
                        }
                    }
                }
                //מצרף למילון סכום ההריגות עד כה
                
                dicAgents.agentWithMissions[agent] = missionSumKills;
            }

            return View(dicAgents);
        }


        //מעלה דף של מטרות
        public async Task<IActionResult> GetTargets()
        {
            var tartgets = await _httpClient.GetFromJsonAsync<IEnumerable<Target>>("http://localhost:5281/targets");

            return View(tartgets);

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult> Map()
        {
            var agents = await _httpClient.GetFromJsonAsync<IEnumerable<Agent>>("http://localhost:5281/Agents");
            var tartgets = await _httpClient.GetFromJsonAsync<IEnumerable<Target>>("http://localhost:5281/targets");
            var AliveTargets = tartgets.Where(t => t.Status == "Alive");
            var map = new Map();
            map.Agents = agents.ToList();
            map.Targets = AliveTargets.ToList();
            return View(map);   
        }


    }
}

ProjectFinal - MVC/Controllers/MissionsController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectFinal___MVC.Models;
using ProjectFinal___MVC.Service;
using System.Net.Http;

namespace ProjectFinal___MVC.Controllers
{
    public class MissionsController : Controller
    {

        private readonly HttpClient _httpClient;
        private readonly ILogger<MissionsController> _logger;

        public MissionsController(ILogger<MissionsController> logger, HttpClient httpClient)
        {
            _logger = logger;
            _httpClient = httpClient;
        }

        public async Task<IActionResult> GetMissions()
        {
            var missions = await _httpClient.GetFromJsonAsync<IEnumerable<Mission>>("http://localhost:5281/Missions");

            var MissionSuggestens = missions.Where(mis => mis.Status == "Suggestion");

            var suggestions = new List<Suggestion>();

            foreach (var mission in MissionSuggestens)
            {
                var suggestion = new Suggestion();

                
                suggestion.agentName = mission.Agent.nickname;
                suggestion.agentLocation = $"({mission.Agent.x}, {mission.Agent.y})";
                
                suggestion.targetName = mission.Target.name;
                suggestion.targetLocation = $"({mission.Target.x}, {mission.Target.y})";

                suggestion.timeLeft = mission.TimLeft.ToString();

                suggestion.distance = Math.Sqrt(Math.Pow(mission.Agent.x - mission.Target.x, 2) + Math.Pow(mission.Agent.y - mission.Target.y, 2)).ToString();

                suggestion.MissionId = mission.Id;

                suggestions.Add(suggestion);
            }

            return View(suggestions);
        }


        public async Task<IActionResult> StartMission(int id)
        {                                      
            var response = await _httpClient.PutAsync($"http://localhost:5281/Missions/{id}", null);

            if (response.IsSuccessStatusCode)
            {
                TempData["Message"] = "Mission has started!";
            }
            else
            {                    
                TempData["Message"] = "cannot start mission that is fardest then 200 km!";               
            }
           
            return RedirectToAction("GetMissions");
        }


        public async Task<IActionResult> ReadMission(int id)
        {
            var missions = await _httpClient.GetFromJsonAsync<IEnumerable<Mission>>("http://localhost:5281/Missions");
            var mission = missions.FirstOrDefault(m => m.Id == id);
            return View(mission);
        }

    }
}

ProjectFinal - MVC/Views/Home/GetAgents.cshtml
@model ProjectFinal___MVC.Service.AgentWithMission

@{
    ViewData["Title"] = "GetAgents";
}

<head>
    <script>
        setTimeout(function () {
            window.location.reload(1);
        }, 5000);
    </script>
</head>
<h1>Get Agents list</h1>

<table class="table">
    <h2>Agents and their Missions</h2>
    <thead>
        <tr>
            <th>Id</th>
            <th>Agent Name</th>
            <th>Photo URL</th>
            <th>Agent Status</th>
            <th>Location</th>
            <th>Mission Link</th>
            <th>Time left to mission</th>
            <th>Sum of Kills</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var agent in Model.agentWithMissions.Keys)
        {
            var missionInfo = Model.agentWithMissions[agent];
            <tr>
                <td>
                    @Html.DisplayFor(_ => agent.Id)
                </td>
                <td>
                    @Html.DisplayFor(_ => agent.nickname)
                </td>
                <td>
                    @Html.DisplayFor(_ => agent.photoUrl)
                </td>
                <td>
                    @Html.DisplayFor(_ => agent.Status)
                </td>
                <td>
                    (@Html.DisplayFor(_ => agent.x), @Html.DisplayFor(_ => agent.y))
                </td>
                @if (missionInfo.mission != null)
                {
                    <td>
                        @Html.ActionLink("Get mission", "ReadMission", "Missions", missionInfo.mission, null)
                    </td>
                    <td>
                        @Html.DisplayFor(_ => missionInfo.mission.TimLeft)
                    </td>
                }
                else
                {
                    <td>
                        No active mission
                    </td>
                    <td>
                        ---
                    </td>
                }
                @if (missionInfo.sumKills != null)
                {
                    <td>
                        @Html.DisplayFor(_ => missionInfo.sumKills)
                </td>
                }
            </tr>
        }
    </tbody>
</table>

ProjectFinal - MVC/Views/Home/GetTargets.cshtml
@model IEnumerable<ProjectFinal___MVC.Models.Target>

@{
    ViewData["Title"] = "GetTargets";
}
<head>
    <script>
        setTimeout(function () {
            window.location.reload(1);
        }, 5000);
    </script>
</head>

<h1>GetTargets</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.photoUrl)
            </th>
            <th>
                Location
            </th>                      
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.position)
            </td>           
            <td>
                @Html.DisplayFor(modelItem => item.photoUrl)
            </td>
            <td>
                (@Html.DisplayFor(_ => item.x), @Html.DisplayFor(_ => item.y))
            </td>                      
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>            
        </tr>
}
    </tbody>
</table>

ProjectFinal - MVC/Views/Home/Index.cshtml
@model ProjectFinal___MVC.Service.Summery

@{
    ViewData["Title"] = "Index";
}
<head>
    <script>
        setTimeout(function () {
            window.location.reload(1);
        }, 5000);
    </script>
</head>

<h1>Home</h1>

<div>
    <h4>Summery</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.agents)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.agents) |
            on a mission: @Html.DisplayFor(model => model.ActiveAgents)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.targets)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.targets) |
            eliminated: @Html.DisplayFor(model => model.ActiveTargets)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.missions)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.missions) |
            active: @Html.DisplayFor(model => model.ActiveMissions)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GanaralRatio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GanaralRatio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleventRatio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleventRatio)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

ProjectFinal - MVC/Views/Home/Map.cshtml
@model ProjectFinal___MVC.Service.Map
<head>
    <script>
        setTimeout(function () {
            window.location.reload(1);
        }, 2500);
    </script>
</head>
<style>
    .grid-container {
        width: 10000px; /* 1000 משבצות * 10 פיקסלים למשבצת */
        height: 10000px;
        border: 2px solid black; /* מסגרת למפה כולה */
        position: relative;
        margin: 0 auto;
        overflow: hidden;
    }

    .grid {
        display: grid;
        grid-template-columns: repeat(1000, 1fr);
        grid-template-rows: repeat(1000, 1fr);
        width: 100%;
        height: 100%;
        position: relative;
    }

    .grid-item {
        width: 10px;
        height: 10px;
        border: 1px solid lightgray;
    }

    .agent, .target {
        position: absolute;
        width: 10px;
        height: 10px;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .agent {
        background-color: blue;
        color: transparent; 
        transition: color 0.3s; 
        position: relative;
    }

    .target {
        background-color: red;
        color: transparent; 
        transition: color 0.3s;
        position: relative;
    }

    .agent:hover::after {
        content: attr(data-id);
        color: white; /* הצג את ה-ID כאשר העכבר מעל */
        position: absolute;
        top: -20px;
        left: 50%;
        transform: translateX(-50%);
        background: black;
        padding: 2px 5px;
        border-radius: 3px;
        font-size: 12px;
        white-space: nowrap;
    }

        .target:hover::after {
            content: attr(data-id);
            color: white; /* הצג את ה-ID כאשר העכבר מעל */
            position: absolute;
            top: -20px;
            left: 50%;
            transform: translateX(-50%);
            background: black;
            padding: 2px 5px;
            border-radius: 3px;
            font-size: 12px;
            white-space: nowrap;
        }
</style>


@foreach (var agent in Model.Agents)
{
<div class="agent" style="left:@(agent.x * 10)px; top:@(agent.y * 10)px;" data-id="@agent.nickname">
                
    </div>
}

@foreach (var target in Model.Targets)
{
<div class="target" style="left:@(target.x * 10)px; top:@(target.y * 10)px;" data-id="@target.name">
                
    </div>
}
</div>
</div>

ProjectFinal - MVC/Views/Missions/GetMissions.cshtml
@model IEnumerable<ProjectFinal___MVC.Service.Suggestion>

@{
    ViewData["Title"] = "GetMissions";
}
<head>
    <script>
        setTimeout(function () {
            window.location.reload(1);
        }, 5000);
    </script>
</head>

<h1>GetMissions</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MissionId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.agentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.agentLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.targetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.targetLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.distance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.timeLeft)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MissionId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.agentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.agentLocation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.targetName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.targetLocation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.distance)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.timeLeft)
            </td>             
            <td>               
                @Html.ActionLink("Start mission", "StartMission", new { id = item.MissionId })
            </td>           
        </tr>
}
    </tbody>
</table>
           
                    
                

ProjectFinal - MVC/Views/Missions/ReadMission.cshtml
@model ProjectFinal___MVC.Models.Mission

@{
    ViewData["Title"] = "ReadMission";
}

<head>
    <script>
        setTimeout(function () {
            window.location.reload(1);
        }, 5000);
    </script>
    <title>@ViewData["Title"]</title>
</head>

<h1>Missions Details</h1>

<div>
    <h4>Mission</h4>
    <hr />
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <strong>Mission Id:</strong> @Html.DisplayFor(model => model.Id)
            </div>
            <div class="col-sm-4">
                <strong>Agent Id:</strong> @Html.DisplayFor(model => model.Agent.Id)
            </div>
            <div class="col-sm-4">
                <strong>Agent's Name:</strong> @Html.DisplayFor(model => model.Agent.nickname)
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <strong>Target Id:</strong> @Html.DisplayFor(model => model.Target.Id)
            </div>
            <div class="col-sm-4">
                <strong>Target's Name:</strong> @Html.DisplayFor(model => model.Target.name)
            </div>
            <div class="col-sm-4">
                <strong>@Html.DisplayNameFor(model => model.Duration):</strong> @Html.DisplayFor(model => model.Duration)
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <strong>@Html.DisplayNameFor(model => model.TimLeft):</strong> @Html.DisplayFor(model => model.TimLeft)
            </div>
            <div class="col-sm-4">
                <strong>@Html.DisplayNameFor(model => model.Status):</strong> @Html.DisplayFor(model => model.Status)
            </div>
        </div>
    </div>
</div>

<a asp-controller="Agents" asp-action="GetAgents">Back to Agents</a>

ProjectFinal - MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectFinal___MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectFinal___MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectFinal___MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Map">Map</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="GetAgents">Agents</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="GetTargets">Targets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Missions" asp-action="GetMissions">Missions</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProjectFinal___MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>